In [1]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv(r"C:\shahil\desk\SHAHIL\deep learning\AI_Human.csv")
data

text           generated
0       Cars. Cars have been around since they became ...  Generated by Human
1       Transportation is a large necessity in most co...  Generated by Human
2       "America's love affair with it's vehicles seem...  Generated by Human
3       How often do you ride in a car? Do you drive a...  Generated by Human
4       Cars are a wonderful thing. They are perhaps o...  Generated by Human
...                                                   ...                 ...
487230  Tie Face on Mars is really just a big misunder...  Generated by Human
487231  The whole purpose of democracy is to create a ...  Generated by Human
487232  I firmly believe that governments worldwide sh...    Generated by AI 
487233  I DFN't agree with this decision because a LFT...  Generated by Human
487234  Richard Non, Jimmy Carter, and Bob Dole and ot...  Generated by Human

[487235 rows x 2 columns]

In [3]:
data.head()

text           generated
0  Cars. Cars have been around since they became ...  Generated by Human
1  Transportation is a large necessity in most co...  Generated by Human
2  "America's love affair with it's vehicles seem...  Generated by Human
3  How often do you ride in a car? Do you drive a...  Generated by Human
4  Cars are a wonderful thing. They are perhaps o...  Generated by Human

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 487235 entries, 0 to 487234
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   text       487235 non-null  object
 1   generated  487235 non-null  object
dtypes: object(2)
memory usage: 7.4+ MB


In [5]:
data.describe()

text           generated
count                                              487235              487235
unique                                             487235                   2
top     Cars. Cars have been around since they became ...  Generated by Human
freq                                                    1              305797

In [6]:
data.isna().any()

text         False
generated    False
dtype: bool

In [7]:
data['generated'].value_counts()

generated
Generated by Human    305797
Generated by AI       181438
Name: count, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
data['text']=le1.fit_transform(data['text'])
data['generated']=le2.fit_transform(data['generated'])

In [10]:
x=data.drop(["generated"],axis=1)
x

text
0        83266
1       445232
2        35397
3       209626
4        79648
...        ...
487230  433564
487231  414992
487232  228032
487233  211025
487234  331900

[487235 rows x 1 columns]

In [11]:
y=data["generated"]
y

0         1
1         1
2         1
3         1
4         1
         ..
487230    1
487231    1
487232    0
487233    1
487234    1
Name: generated, Length: 487235, dtype: int32

In [12]:
data["generated"].value_counts()

generated
1    305797
0    181438
Name: count, dtype: int64

In [14]:
xtrain,xtest,ytrain,ytest,=train_test_split(x,y,train_size=0.3,random_state=42)

In [16]:
scaler = MinMaxScaler()
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)
xtrain_scaled

array([[0.65305921],
       [0.11138203],
       [0.06598896],
       ...,
       [0.04720534],
       [0.64199059],
       [0.14072323]])

In [17]:
xtrain_scaled.shape

(146170, 1)

In [132]:
import tensorflow as tf
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(6,activation="relu"))
ann.add(tf.keras.layers.Dense(3,activation="relu"))
ann.add(tf.keras.layers.Dense(1,activation="sigmoid"))
#compiling Ann
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
#fit
ann.fit(xtrain_scaled,ytrain,batch_size=32,epochs=100)

Epoch 1/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.6104 - loss: 0.6688
Epoch 2/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.6251 - loss: 0.6615
Epoch 3/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.6288 - loss: 0.6597
Epoch 4/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6283 - loss: 0.6599
Epoch 5/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.6260 - loss: 0.6611
Epoch 6/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6284 - loss: 0.6598
Epoch 7/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.6271 - loss: 0.6605
Epoch 8/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6270 - loss: 0.6605
Epoch 9/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6283 - loss: 0.6599
Epoch 10/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.6292 - loss: 0.6594
Epoch 11/100
4568/4568 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6255 - loss: 0.6613
Epoch 12/100
4568/4

In [146]:
ypred = ann.predict(xtest_scaled)
ypred

10659/10659 ━━━━━━━━━━━━━━━━━━━━ 10s 971us/step


array([[0.6262338],
       [0.6262338],
       [0.6262338],
       ...,
       [0.6262338],
       [0.6262338],
       [0.6262338]], dtype=float32)

In [148]:
ypred_classes=ypred.argmax(axis=1)
ypred_classes

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [150]:
prediction=ann.predict(scaler.transform([[83266]]))
if prediction>0.5:
    print("Generated by AI")
else:
    print("Generated by Human")
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
Generated by AI
[[0.6262338]]


C:\Users\Power User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [152]:
ann.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 6)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 3)              │            21 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113 (456.00 B)

 Trainable params: 37 (148.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 76 (308.00 B)

In [154]:
ann.evaluate(xtest_scaled,ytest)

10659/10659 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step - accuracy: 0.6264 - loss: 0.6608


[0.660135805606842, 0.6278421878814697]

# prediction through user input

In [158]:
text = str(input("Enter a Text:"))

Enter a Text: You are Shahil, a person with a strong interest in data analytics, investing, and swing trading in India. You have skills in AWS and Google Cloud, and you work as a trainer in data analytics, possibly through your business called Skillride. You trade using Upstox as your broker. You're a night person, usually sleeping from 1 AM to 6 AM, and you’re also focused on gaining weight healthily. Additionally, you observed Islamic fasting recently, showing discipline and spiritual commitment.


In [160]:
text = le1.fit_transform([text])
pred = ann.predict(scaler.transform([[text[0]]]))
if pred>0.5:
    print("Generated by AI")
else:
    print("Generated by Human")
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
Generated by AI
[[0.6262338]]


C:\Users\Power User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


# Build Gradio App

In [162]:
!pip3 install gradio

In [164]:
def fun(text):
    text = le1.fit_transform([text])
    pred = ann.predict(scaler.transform([[text[0]]]))
    if pred>0.5:
        return "Generated by AI"
    else:
        return "Generated by Human"
        
fun("hello")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


C:\Users\Power User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


'Generated by AI'

In [70]:
import gradio as gr

In [73]:
headline ="AI vs Human Generated Text classification"
iface = gr.Interface(fn=fun,inputs= "text",outputs="text",title=headline)
iface.launch(share=True)

* Running on local URL:  http://127.0.0.1:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.


In [75]:
ann.save("Text Generated by AI or Human.h5")

In [77]:
from tensorflow.keras.models import load_model
model=load_model('Text Generated by AI or Human.h5')
model

<Sequential name=sequential, built=True>

In [ ]:
# ?code used to sho all values
# import numpy as np
# np.set_printoptions(threshold=np.inf, precision=8, suppress=True)