In [41]:
import warnings
warnings.filterwarnings("ignore")

In [42]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

In [43]:
data=pd.read_csv(r"E:\mini project\archive (4)\indian_startups_by_state.csv")
data

S No.  Year                        State  \
0         1  2023  Andaman and Nicobar Islands   
1         2  2023  Andaman and Nicobar Islands   
2         3  2023  Andaman and Nicobar Islands   
3         4  2023  Andaman and Nicobar Islands   
4         5  2023  Andaman and Nicobar Islands   
...     ...   ...                          ...   
7086   7087  2016                   Tamil Nadu   
7087   7088  2016                    Telangana   
7088   7089  2016                Uttar Pradesh   
7089   7090  2016                  Uttarakhand   
7090   7091  2016                  West Bengal   

                                 Industry  Count          Last Update  
0     AR VR (Augmented + Virtual Reality)      2  18-06-2023 04:00:02  
1                              Automotive      1  18-06-2023 04:00:02  
2                            Construction      2  18-06-2023 04:00:02  
3                             IT Services      1  18-06-2023 04:00:02  
4                        Travel & Tourism      1  18-06-2023 04:00:02  
...                                   ...    ...                  ...  
7086                        NOT SPECIFIED     55  18-06-2023 04:00:02  
7087                        NOT SPECIFIED     20  18-06-2023 04:00:02  
7088                        NOT SPECIFIED     29  18-06-2023 04:00:02  
7089                        NOT SPECIFIED      4  18-06-2023 04:00:02  
7090                        NOT SPECIFIED      8  18-06-2023 04:00:02  

[7091 rows x 6 columns]

In [44]:
data.drop(["S No.","Last Update"],axis=1,inplace=True)
data

Year                        State                             Industry  \
0     2023  Andaman and Nicobar Islands  AR VR (Augmented + Virtual Reality)   
1     2023  Andaman and Nicobar Islands                           Automotive   
2     2023  Andaman and Nicobar Islands                         Construction   
3     2023  Andaman and Nicobar Islands                          IT Services   
4     2023  Andaman and Nicobar Islands                     Travel & Tourism   
...    ...                          ...                                  ...   
7086  2016                   Tamil Nadu                        NOT SPECIFIED   
7087  2016                    Telangana                        NOT SPECIFIED   
7088  2016                Uttar Pradesh                        NOT SPECIFIED   
7089  2016                  Uttarakhand                        NOT SPECIFIED   
7090  2016                  West Bengal                        NOT SPECIFIED   

      Count  
0         2  
1         1  
2         2  
3         1  
4         1  
...     ...  
7086     55  
7087     20  
7088     29  
7089      4  
7090      8  

[7091 rows x 4 columns]

In [45]:
ob1=LabelEncoder()
ob2=LabelEncoder()

In [46]:
data["State"]=ob1.fit_transform(data["State"])
data["Industry"]=ob2.fit_transform(data["Industry"])
data

Year  State  Industry  Count
0     2023      0         1      2
1     2023      0        10      1
2     2023      0        14      2
3     2023      0        27      1
4     2023      0        55      1
...    ...    ...       ...    ...
7086  2016     31        33     55
7087  2016     32        33     20
7088  2016     34        33     29
7089  2016     35        33      4
7090  2016     36        33      8

[7091 rows x 4 columns]

In [47]:
x=data.drop(["Count"],axis=1)
y=data["Count"]

In [48]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=9)

In [49]:
len(xtest)

1419

## Random Forest Regressor

In [50]:
from sklearn.ensemble import RandomForestRegressor

In [51]:
model4=RandomForestRegressor()
model4.fit(xtrain,ytrain)

RandomForestRegressor()

In [52]:
print(model4.score(xtrain,ytrain))
print(model4.score(xtest,ytest))

0.9636070050504977
0.798752145748227


In [53]:
model4.predict([[2023,0,27]])

array([5.31])

In [54]:
import numpy as np

year = int(input("year"))
state = input("state")
state = ob1.transform([state])

industry = input("industry")
industry = ob2.transform([industry])
print("Transformed state shape:", state.shape)
print("Transformed industry shape:", industry.shape)
user_input = np.array([[year, *state, *industry]])
print("User input shape:", user_input.shape)

prediction = model4.predict(user_input)
print("Prediction:", int(prediction))

year2022
stateKerala
industryAutomotive
Transformed state shape: (1,)
Transformed industry shape: (1,)
User input shape: (1, 3)
Prediction: 21


## Decision Tree Regressor

In [55]:
model=DecisionTreeRegressor()
model.fit(xtrain,ytrain)

DecisionTreeRegressor()

In [56]:
print(model.score(xtrain,ytrain))
print(model.score(xtest,ytest))

1.0
0.7676369826335404


In [57]:
model.predict([[2023,16,27]])

array([102.])

## Linear Regression

In [58]:
from sklearn.linear_model import LinearRegression

In [59]:
model2=LinearRegression()
model2.fit(xtrain,ytrain)

LinearRegression()

In [60]:
print(model2.score(xtrain,ytrain))
print(model2.score(xtest,ytest))

0.01600086421941249
0.01617756190617048


## Support Vector Regression

In [61]:
from sklearn.svm import SVR

In [62]:
model3=SVR()
model3.fit(xtrain,ytrain)

SVR()

In [63]:
print(model3.score(xtrain,ytrain))
print(model3.score(xtest,ytest))

-0.11037602412472602
-0.09764600550919544


## Random Forest Regressor

In [64]:
from sklearn.ensemble import RandomForestRegressor

In [65]:
model4=RandomForestRegressor()
model4.fit(xtrain,ytrain)

RandomForestRegressor()

In [66]:
print(model4.score(xtrain,ytrain))
print(model4.score(xtest,ytest))

0.9627190621460957
0.7981600249247077


In [67]:
model.predict([[2023,16,27]])

array([102.])

## Gradient Boosting Regressor

In [68]:
from sklearn.ensemble import GradientBoostingRegressor

In [69]:
model5=GradientBoostingRegressor()
model5.fit(xtrain,ytrain)

GradientBoostingRegressor()

In [70]:
print(model5.score(xtrain,ytrain))
print(model5.score(xtest,ytest))

0.4319823980688955
0.3998940538780268


## KNeighborsRegressor

In [71]:
from sklearn.neighbors import KNeighborsRegressor

In [72]:
model6=KNeighborsRegressor()
model6.fit(xtrain,ytrain)

KNeighborsRegressor()

In [73]:
print(model6.score(xtrain,ytrain))
print(model6.score(xtest,ytest))

0.5627474516002124
0.3591744990506349
