In [1]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

In [4]:
data=pd.read_csv(r"C:\Users\Power User\Downloads\indian_startups_by_state.csv")
data

S No.  Year                        State  \
0         1  2023  Andaman and Nicobar Islands   
1         2  2023  Andaman and Nicobar Islands   
2         3  2023  Andaman and Nicobar Islands   
3         4  2023  Andaman and Nicobar Islands   
4         5  2023  Andaman and Nicobar Islands   
...     ...   ...                          ...   
7086   7087  2016                   Tamil Nadu   
7087   7088  2016                    Telangana   
7088   7089  2016                Uttar Pradesh   
7089   7090  2016                  Uttarakhand   
7090   7091  2016                  West Bengal   

                                 Industry  Count          Last Update  
0     AR VR (Augmented + Virtual Reality)      2  18-06-2023 04:00:02  
1                              Automotive      1  18-06-2023 04:00:02  
2                            Construction      2  18-06-2023 04:00:02  
3                             IT Services      1  18-06-2023 04:00:02  
4                        Travel & Tourism      1  18-06-2023 04:00:02  
...                                   ...    ...                  ...  
7086                        NOT SPECIFIED     55  18-06-2023 04:00:02  
7087                        NOT SPECIFIED     20  18-06-2023 04:00:02  
7088                        NOT SPECIFIED     29  18-06-2023 04:00:02  
7089                        NOT SPECIFIED      4  18-06-2023 04:00:02  
7090                        NOT SPECIFIED      8  18-06-2023 04:00:02  

[7091 rows x 6 columns]

In [5]:
data.drop(["S No.","Last Update"],axis=1,inplace=True)
data

Year                        State                             Industry  \
0     2023  Andaman and Nicobar Islands  AR VR (Augmented + Virtual Reality)   
1     2023  Andaman and Nicobar Islands                           Automotive   
2     2023  Andaman and Nicobar Islands                         Construction   
3     2023  Andaman and Nicobar Islands                          IT Services   
4     2023  Andaman and Nicobar Islands                     Travel & Tourism   
...    ...                          ...                                  ...   
7086  2016                   Tamil Nadu                        NOT SPECIFIED   
7087  2016                    Telangana                        NOT SPECIFIED   
7088  2016                Uttar Pradesh                        NOT SPECIFIED   
7089  2016                  Uttarakhand                        NOT SPECIFIED   
7090  2016                  West Bengal                        NOT SPECIFIED   

      Count  
0         2  
1         1  
2         2  
3         1  
4         1  
...     ...  
7086     55  
7087     20  
7088     29  
7089      4  
7090      8  

[7091 rows x 4 columns]

In [6]:
data["State"].unique()

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra and Nagar Haveli and Daman and Diu',
       'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh',
       'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry',
       'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana',
       'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
       'NOT SPECIFIED'], dtype=object)

In [8]:
ob1=LabelEncoder()
ob2=LabelEncoder()

In [9]:
data["State"]=ob1.fit_transform(data["State"])
data["Industry"]=ob2.fit_transform(data["Industry"])
data

Year  State  Industry  Count
0     2023      0         1      2
1     2023      0        10      1
2     2023      0        14      2
3     2023      0        27      1
4     2023      0        55      1
...    ...    ...       ...    ...
7086  2016     31        33     55
7087  2016     32        33     20
7088  2016     34        33     29
7089  2016     35        33      4
7090  2016     36        33      8

[7091 rows x 4 columns]

In [10]:
x=data.drop(["Count"],axis=1)
y=data["Count"]

In [11]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=9)

In [12]:
len(xtest)

1419

## Random Forest Regressor

In [15]:
from sklearn.ensemble import RandomForestRegressor

In [16]:
model4=RandomForestRegressor()
model4.fit(xtrain,ytrain)

RandomForestRegressor()

In [17]:
print(model4.score(xtrain,ytrain))
print(model4.score(xtest,ytest))

0.9637899878784897
0.8173209252503348


In [18]:
model4.predict([[2023,0,27]])

array([6.2])

In [31]:
import numpy as np

year = int(input("year"))
state = input("state")
state = ob1.transform([state])

industry = input("industry")
industry = ob2.transform([industry])
print("Transformed state shape:", state.shape)
print("Transformed industry shape:", industry.shape)
user_input = np.array([[year, *state, *industry]])
print("User input shape:", user_input.shape)

prediction = model4.predict(user_input)
print("Prediction:", int(prediction))

year 2023
state Kerala
industry IT Services


Transformed state shape: (1,)
Transformed industry shape: (1,)
User input shape: (1, 3)
Prediction: 117


## Decision Tree Regressor

In [33]:
model=DecisionTreeRegressor()
model.fit(xtrain,ytrain)

DecisionTreeRegressor()

In [35]:
print(model.score(xtrain,ytrain))
print(model.score(xtest,ytest))

1.0
0.7667773470494103


In [37]:
model.predict([[2023,16,27]])

array([102.])

## Linear Regression

In [41]:
from sklearn.linear_model import LinearRegression

In [43]:
model2=LinearRegression()
model2.fit(xtrain,ytrain)

LinearRegression()

In [44]:
print(model2.score(xtrain,ytrain))
print(model2.score(xtest,ytest))

0.01600086421941227
0.016177561906170368


## Support Vector Regression

In [49]:
from sklearn.svm import SVR

In [51]:
model3=SVR()
model3.fit(xtrain,ytrain)

SVR()

In [52]:
print(model3.score(xtrain,ytrain))
print(model3.score(xtest,ytest))

-0.11037602412472602
-0.09764600550919544


## Random Forest Regressor

In [55]:
from sklearn.ensemble import RandomForestRegressor

In [56]:
model4=RandomForestRegressor()
model4.fit(xtrain,ytrain)

RandomForestRegressor()

In [57]:
print(model4.score(xtrain,ytrain))
print(model4.score(xtest,ytest))

0.9639328921691711
0.8052950583360934


In [58]:
model.predict([[2023,16,27]])

array([102.])

## Gradient Boosting Regressor

In [61]:
from sklearn.ensemble import GradientBoostingRegressor

In [62]:
model5=GradientBoostingRegressor()
model5.fit(xtrain,ytrain)

GradientBoostingRegressor()

In [63]:
print(model5.score(xtrain,ytrain))
print(model5.score(xtest,ytest))

0.4319823980688956
0.3998940538780268


## KNeighborsRegressor

In [66]:
from sklearn.neighbors import KNeighborsRegressor

In [67]:
model6=KNeighborsRegressor()
model6.fit(xtrain,ytrain)

KNeighborsRegressor()

In [68]:
print(model6.score(xtrain,ytrain))
print(model6.score(xtest,ytest))

0.5627474516002124
0.3591744990506349


# Build Gradio App

In [70]:
!pip3 install gradio

In [112]:
def fun(year,state,industry):
    state_encoded = ob1.transform([state])
    industry_encoded = ob2.transform([industry])
    pred = model4.predict([[year,state_encoded[0],industry_encoded[0]]])
    return int(pred)
        
fun(2023,"Kerala","IT Services")

131

In [114]:
import gradio as gr

In [116]:
headline ="Number of startups App"
iface = gr.Interface(fn=fun,inputs=[
        gr.Number(label="year"),
        gr.Textbox(label="state"),
        gr.Textbox(label="industry")],
        outputs=[gr.Textbox(label="Startups Count")],title=headline)
iface.launch(share=True)

* Running on local URL:  http://127.0.0.1:7867

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.
